title: Mozilla Winter of Security
link: "https://wiki.mozilla.org/Security/Automation/Winter_Of_Security_2016"
description: >-
  The Winter of Security (MWOS) is a program organized by Mozilla's Security teams to involve students with Security projects. Students who have to perform a semester project as part of their university curriculum can apply to one of the MWOS projects.
section: 🔓 Open Source Websites
tag: open-source-websites