title: The Open Web Application Security Project (OWASP)
link: "https://www.owasp.org"
description: OWASP is an open community dedicated to enabling organizations to conceive, develop, acquire, operate, and maintain applications that can be trusted.
section: 🗣️ General Coding advice
tag: general-coding-advice